name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    outputs:
      branch_name: ${{ steps.build.outputs.branch }}
      app_version: ${{ steps.build.outputs.app_version }}
    env:
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Setup Registry
        env:
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}
        id: registry
        run: echo "$NPM_REGISTRY" > $HOME/.npmrc

      - name: Version
        id: version
        run: |
          export APP_VERSION=$(grep version package.json | sed 's/.*"version": "\(.*\)".*/\1/' | sed 's/-.*//')
          export BRANCH_VERSION=$(echo ${GITHUB_REF#refs/heads/})
          export BRANCH_VERSION=$(echo ${BRANCH_VERSION#refs/tags/})
          npm install
          if [[ ! $GITHUB_REF = refs/tags/* ]]; then
            sed -i "s/\"version\": \".*\"/\"version\": \"$APP_VERSION-$BRANCH_VERSION.$(date +%Y%m%d%H%M%S)\"/" package.json
          else
            sed -i "s/\"version\": \".*\"/\"version\": \"${BRANCH_VERSION#v}\"/" package.json
          fi

      - name: Build
        id: build
        run: npm run build

      - name: Publish Artifacts
        id: publish
        run: |
          cp package.json README.md dist
          cd dist
          npm publish
          if [[ $GITHUB_REF = refs/tags/* ]]; then
            npm publish --@goplayerzero:registry=https://registry.npmjs.org/
          fi
